<!DOCTYPE html>
<html>
<head>
	<title>Fanie_54384508</title>
</head>
<body>
	<a href='index.php'>Index</a> |
	<a href='Task1.php'>Task1</a> |
	<a href='Task2.php'>Task2</a> |
	<a href='Task3.php'>Task3</a> |
	<a href='Task4.php'>Task4</a> |
	<a href='Task5.php'>Task5</a> |
	<a href='Task6.php'>Task6</a> |
	<a href='Task7.php'>Task7</a> |
	<a href='Task8.php'>Task8</a> |
	<a href='Task9.php'>Task9</a> | 
	<a href='Task10.php'>Task10</a> |
	<a href='Task11.php'>Task11</a> 
</body>
</html>